### PR TITLE
Enable kubernetes autoupdate on cluster create

### PR DESCRIPTION
**Pull request by majst01**
This should be enabled now by default. @chbmuc must define the date when this should be released.

### CODE REVIEW

**Comment by mwennrich** [comment]
won't work that way, because of
```
if viper.IsSet("autoupdate-kubernetes") || viper.IsSet("autoupdate-machineimages") || purpose == string(v1beta1.ShootPurposeEvaluation)
```
defaults are set in cloud-api/defaultClusterCreateRequest

**Comment by majst01** [comment]
> defaultClusterCreateRequest

OK, will create an additional PR for cloud-api

**Comment by Gerrit91** [comment]
It is also better to set defaults in the server rather than in the client because for client versions we are not in control.

**Comment by Gerrit91** [comment]
Implemented server-side.

**Pull request closed without merging**
