### PR TITLE
Add cluster issues command and other tweaks.

### PR DESCRIPTION
**Pull request by Gerrit91**
- Add `cluster issues` command (is slower than `cluster ls` especially for bigger systems)
- `cluster issues <cluster-id>` shows explicit required actions for a cluster
- Show actual size of the cluster (except for `cluster ls` because this would become slow) 
- Show last errors and last operations in `cluster logs` command

### CODE REVIEW

**Comment by majst01** [comment]
Some hints:
- firewalls are sorted into machines when `cluster machine ls` is called
- i would put the required actions either at the end of the whole list in the `cluster machine ls` in the same way this happens during `cluster describe`

Like this approach, because no server side modifications required

**Comment by Gerrit91** [comment]
Good hints, thank you. I hope the last commit implements your suggestions.

**Review by majst01 — APPROVED** [review]
quite a beast, LGTM

**Review by mwennrich — APPROVED** [review]

**Comment by Gerrit91** [comment]
Was quite a lot of "back and forth", but I think it has finally made it into an appropriate shape. Thanks to both of you for helping me out. :)

**Pull request merged**
