### PR TITLE
Add volume panel to dashboard

### PR DESCRIPTION
**Pull request by Gerrit91**

### CODE REVIEW

**Comment by majst01** [comment]
would be a great addition if filters can be set from the dashboard, maybe in the next iteration

**Comment by Gerrit91** [comment]
Yes, I was thinking about this already, too. Would make a lot of sense.

**Comment by majst01** [comment]
pull master and tagged cloud-go required

**Comment by majst01** [comment]
Problem for normal (non providertenant) users, if they select the volume tab, only errors are shown right ?
Maybe disable this tab if !providertenant

**Comment by Gerrit91** [comment]
> Problem for normal (non providertenant) users, if they select the volume tab, only errors are shown right ?

It just displays the upper half.

**Review by majst01 — APPROVED** [review]

**Pull request merged**
